### ISSUE TITLE
How to run ease commands with npm?

### ISSUE THREAD

**Issue by besrabasant** [cgnetwork/laravel-ease#5]

**Comment by cgnetwork** [comment]
Hi, thanks for opening the issue.

As of version `0.7.0` the package now uses npm, to better align with a default Laravel install.

Please upgrade the package by first running `composer upgrade cgnetwork/ease --dev`

Once upgraded, please run `php artisan ease:install` which will update your `package.json` ease scripts.

Finally, `npm run ease:install` then `npm run ease` will start your dev server.
